### ISSUE TITLE
Wednesday 3/8/2017 Standup meeting

### ISSUE THREAD

**Issue by SidHarder** [ipfs/test-lab#21]
The next InterPlanetary Test Lab standup will be held on:

Wedneday 3-Mar 19:00 UTC

HackMd Agenda -https://hackmd.io/IwTgDALGCmDGBMBaesBmFERCWiBGA7AGzSLQgAcKwU805QA=

**Comment by FrankPetrilli** [comment]
Do we have a zoom link yet?

**Comment by jbenet** [comment]
Sounds good! i'll be there.

**Comment by jbenet** [comment]
Ahh, sorry, i can't do 17:00 UTC. If people could do later (eg 19:00 UTC), great. Otherwise please record it.

At this point:
- @FrankPetrilli should be close to (if not already) done with the orchestrator parts. 
  - particularly: #13 #14 #15 #16 #17 #18
- @jonnycrunch should be starting to (if not already) test out setting up lablets, and orchestrator, using #17 and #18 
- @whyrusleeping, @hsanjuan, and @dgrisham should have started (or close to) writing their tests to run on the orchestrator
- @jbenet has already started the Job Bundling format spec

**Comment by SidHarder** [comment]
I'm good with 19:00 UTC, I'll get the word out.

**Comment by jonnycrunch** [comment]
19:00 UTC is fine with me.

**Comment by dgrisham** [comment]
19:00 UTC is good with me as well.

**Comment by SidHarder** [comment]
@jbenet I will need someone to setup the zoom link for this meeting and post it.

**Comment by SidHarder** [comment]
Zoom linke: https://zoom.us/j/426123496

**Comment by jbenet** [comment]
Ooof sorry everyone didn't see the change went trough till now. Looked it
up a bit ago but somehow my email search didn't show it. I'll brt
